### PR TITLE
Bring up-to-date with WordPress 4.3

### PR DESCRIPTION
**Pull request by johnjamesjacoby**

### CODE REVIEW

**Comment by bradvin** [comment]
I tested this with WP 4.3 and I am getting missing icons:
image

**Comment by johnjamesjacoby** [comment]
That's what it looks like for me before this pull-request.

**Comment by johnjamesjacoby** [comment]
screen shot 2015-08-25 at 4 08 32 pm

**Comment by field2** [comment]
Some icons were added to the last version. Could that have affected things? https://developer.wordpress.org/resource/dashicons/#album shows all the current icons and their unicode names.

**Comment by johnjamesjacoby** [comment]
> Some icons were added to the last version. Could that have affected things?

Correct. To be clear (and maybe overly verbose) my pull request brings this plugin up-to-speed with the dashicons most recently packagedin WordPress 4.3. Without my pull request, many icons appear as empty while boxes.

**Pull request merged**
